# Generated by Django 5.1.3 on 2024-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('product', models.CharField(max_length=50)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
