# Generated by Django 5.1.3 on 2024-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.IntegerField(),
        ),
    ]
